---
# tasks file for roles/server

- name: Install a list of packages
  yum:
    name:
      - epel-release
    state: present

- name: APP | Install Dependencies
  shell: yum install -y python36 python36-devel python36-setuptools bash
  args:
    warn: no 

- name: APP | Install easy_install
  shell: easy_install-3.6 pip
  args:
    warn: no 
    
- name: APP | Install Docker Module for Python
  pip:
    name: docker-py
    executable: pip
    state: latest
    
- name: APP | Pull default Docker image
  docker_image:
    name: "{{ default_container_image }}"
    source: pull

# Creates the number of containers defined by the variable create_containers, using values from vars file
- name: APP | Create default containers
  docker_container:
    name: "{{ default_container_name }}{{ item }}"
    image: "{{ default_container_image }}"
    command: "{{ default_container_command }}"
    state: present
  with_sequence: count={{ create_containers }}
