---
# tasks file for roles/common

- name: Docker | Upgrade all packages
  yum: name=* state=latest


- name: Docker | Check if Docker is installed
  command: systemctl status docker
  register: docker_check
  ignore_errors: yes  
      
- name: Docker | Download the Docker installer
  get_url:
    url: https://get.docker.com/
    dest: /root/install_docker.sh
    mode: 0700
  when: docker_check.stderr.find('service could not be found') != -1

- name: Docker | Install Docker
  shell: /root/install_docker.sh
  when: docker_check.stderr.find('service could not be found') != -1

- name: Docker | Remove the Docker installer file.
  file:
    state: absent
    path: /root/install_docker.sh

- name: Docker | Enable the Docker daemon in systemd
  systemd:
    name: docker
    enabled: yes
    masked: no

- name: Docker | Start the Docker daemon
  systemd:
    name: docker
    state: started
    masked: no

- name: Docker | Check if Docker Compose is installed
  command: docker-compose --version
  register: docker_compose_check
  ignore_errors: yes

- name: Docker | Download and install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.25.1/docker-compose-`uname -s`-`uname -m`
    dest: /usr/bin/docker-compose
    mode: 0755
  when:
    - docker_compose_check.msg is defined
    - docker_compose_check.msg.find('No such file or directory') != -1
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
             
